# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04d93da32f7e6c578b9566923726d5c89ee76f5421524aa84a46c5eeba32d153ef2ea2561ade96b17d250e6fb032d5bdbb4c9c2cf04dbdc3f045b299c5190691

test:
  secret_key_base: f804a34bfb50ff10b1899e44393c07e8d1fc0ddd6c9a33a6921fabb325438c1e57336ff3b5b11c3829aaa49db00ebe4b5e550580bb4e4ebef076276154c8ae04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
